package dora

import (
	"context"
	"encoding/json"
	"testing"
)

func TestCompactMessagesKeepsAllWhenFewerRounds(t *testing.T) {
	history := []Message{
		{Role: RoleSystem, Content: "sys"},
		{Role: RoleUser, Content: "u1"},
		{Role: RoleAssistant, Content: "a1"},
		{Role: RoleTool, ToolCallID: "c1", Content: "t1"},
		{Role: RoleAssistant, Content: "a2"},
	}
	got := compactMessages(history, 16)
	if len(got) != len(history) {
		t.Fatalf("len = %d, want %d", len(got), len(history))
	}
}

func TestCompactMessagesKeepsRecentRounds(t *testing.T) {
	history := []Message{
		{Role: RoleSystem, Content: "sys"},
		{Role: RoleUser, Content: "u1"},
		{Role: RoleAssistant, Content: "a1"},
		{Role: RoleTool, ToolCallID: "c1", Content: "t1"},
		{Role: RoleAssistant, Content: "a2"},
		{Role: RoleTool, ToolCallID: "c2", Content: "t2"},
		{Role: RoleAssistant, Content: "a3"},
	}
	got := compactMessages(history, 2)
	// Keep system + user + last 2 rounds (a2/t2 and a3).
	want := []Message{
		{Role: RoleSystem, Content: "sys"},
		{Role: RoleUser, Content: "u1"},
		{Role: RoleAssistant, Content: "a2"},
		{Role: RoleTool, ToolCallID: "c2", Content: "t2"},
		{Role: RoleAssistant, Content: "a3"},
	}
	if len(got) != len(want) {
		t.Fatalf("len = %d, want %d; got %#v", len(got), len(want), got)
	}
	for i := range want {
		if got[i].Role != want[i].Role || got[i].Content != want[i].Content {
			t.Fatalf("message %d = %#v, want %#v", i, got[i], want[i])
		}
	}
}

func TestCompactMessagesKeepsRoundIntact(t *testing.T) {
	// A round with multiple tool messages must never be split.
	history := []Message{
		{Role: RoleUser, Content: "u1"},
		{Role: RoleAssistant, Content: "a1", ToolCalls: []ToolCall{{ID: "c1"}, {ID: "c2"}}},
		{Role: RoleTool, ToolCallID: "c1", Content: "t1"},
		{Role: RoleTool, ToolCallID: "c2", Content: "t2"},
		{Role: RoleAssistant, Content: "a2"},
	}
	got := compactMessages(history, 1)
	// Keep user + last round (a2). The a1 round (with its tools) is dropped.
	if len(got) != 2 {
		t.Fatalf("len = %d, want 2; got %#v", len(got), got)
	}
	if got[0].Role != RoleUser || got[1].Role != RoleAssistant || got[1].Content != "a2" {
		t.Fatalf("got %#v", got)
	}
}

func TestCompactMessagesNoAssistantKeepsAll(t *testing.T) {
	history := []Message{
		{Role: RoleSystem, Content: "sys"},
		{Role: RoleUser, Content: "u1"},
	}
	got := compactMessages(history, 2)
	if len(got) != 2 {
		t.Fatalf("len = %d, want 2", len(got))
	}
}

func TestCompactMessagesZeroKeepsAll(t *testing.T) {
	history := []Message{{Role: RoleUser, Content: "u1"}}
	got := compactMessages(history, 0)
	if len(got) != 1 {
		t.Fatalf("len = %d, want 1", len(got))
	}
}

func TestRequestMessagesWithinBudgetIsUnchanged(t *testing.T) {
	// Build history with fewer rounds than the fixed default threshold; it must
	// be returned unchanged.
	history := make([]Message, 0, defaultCompactionRounds)
	history = append(history, Message{Role: RoleSystem, Content: "sys"})
	for i := 0; i < defaultCompactionRounds; i++ {
		history = append(history, Message{Role: RoleUser, Content: "u"})
	}
	a := &Agent{}
	got := a.requestMessages(history)
	if len(got) != len(history) {
		t.Fatalf("len = %d, want %d", len(got), len(history))
	}
}

func TestAgentRunAppliesCompaction(t *testing.T) {
	// Seed enough seeded rounds so that, combined with the round generated by
	// the tool loop, the history exceeds the fixed budget and compaction keeps
	// exactly the leading user message plus the last defaultCompactionRounds
	// rounds.
	const seedRounds = defaultCompactionRounds + 16
	var calls int
	model := modelFunc(func(_ context.Context, request Request) (Response, error) {
		calls++
		switch calls {
		case 1:
			return Response{ToolCalls: []ToolCall{{ID: "c1", Name: "snap", Input: json.RawMessage(`{}`)}}}, nil
		case 2:
			// Compaction keeps leading user message + last 32 rounds (each an
			// assistant plus its tool message).
			want := 1 + 2*defaultCompactionRounds
			if len(request.Messages) != want {
				t.Fatalf("message count = %d, want %d", len(request.Messages), want)
			}
			if request.Messages[0].Role != RoleUser {
				t.Fatalf("first message = %#v, want user", request.Messages[0])
			}
			// The last round is the one produced by this run's tool loop.
			last := request.Messages[len(request.Messages)-2:]
			if last[0].Role != RoleAssistant || last[1].Role != RoleTool ||
				last[1].ToolCallID != "c1" {
				t.Fatalf("last round = %#v", last)
			}
			return Response{Content: "done"}, nil
		default:
			t.Fatal("model called too many times")
			return Response{}, nil
		}
	})
	tool := stubTool{
		spec: ToolSpec{Name: "snap"},
		execute: func(context.Context, json.RawMessage) (string, error) {
			return "ok", nil
		},
	}
	agent, err := New(model, tool)
	if err != nil {
		t.Fatal(err)
	}
	// Seed enough history so the second call exceeds the fixed round budget.
	turn := NewTurn("", "u0")
	for i := 0; i < seedRounds; i++ {
		turn.rounds = append(turn.rounds, Round{
			Assistant: Message{Role: RoleAssistant, Content: "a"},
			Tools:     []Message{{Role: RoleTool, Content: "t", ToolCallID: "cx"}},
		})
	}
	if err := agent.Run(context.Background(), turn); err != nil {
		t.Fatal(err)
	}
	if calls != 2 {
		t.Fatalf("calls = %d", calls)
	}
}